### ISSUE TITLE
Which ubuntu versions correspond to what debian versions?

### ISSUE THREAD

**Issue by libBletchley** [Bylon/TOR_Middlebox#2]
The docs say "For Ubuntu 16.04" and "For Ubuntu 14.04".  What if I have Debian 8?

The docs should mention the version of the tool in question, not the distribution version.

Also, the docs say to create this config file: `/etc/NetworkManager/dnsmasq.d/middlebox.conf`.  We have that path in Debian, but was also have a `/etc/dnsmasq.conf`.  What should be done with `/etc/dnsmasq.conf`?

(edit) there is this mapping:

https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on

which could be useful for Debian users, but really the docs should reference the relevant tool versions so the guide is distro-agnostic.

It's also worth mentioning that the ubuntu 14.4/how-to-forge approach **was** working on Debian Stretch, but broke recently (at least for me).  I'm not sure if that breakage is due to an autoupdate that perhaps crossed the dnsmasq version where shit happened.  But the question then becomes, should I do `sudo apt-get remove dnsmasq` (since the ubuntu 16.04 neglects to install it)?

Great repo, btw.  Apart from the nit-picks above, your doc writing style is excellent.  You give the steps, followed by detailed rationale, which is quite useful.

**Comment by Bylon** [comment]
Hi, actually it says so (sort of)!

I'll try to come up with a text to make it clearer.

Not sure about Debian, since Ubuntu customizes it a lot. Basically if you have SystemD, you should follow the instructions for 16.04, if you are pre-SystemD, so still with Init System V, you'd probably better looking at 14.04

As for dnsmasq, it does what a lot of daemons do. The directory */dnsmasq.d is there so that you can apply your own bit of configuration without having to alter dnsmasq.conf

The daemon reads dnsmasq.conf, then reads all the files you have in dnsmasq.d and add them to the configuration. So normally you should **NOT** change anything in dnsmasq.conf

However, if you feel the dnsmasq you are running have bugs and don't read your piece of configuration, you can alternatively append the content of dnsmaq.d/middlebox.conf to dnsmasq.conf, and remove middlebox.conf.

If you have a full "walkthrough" for Debian 8/Jessie, feel free to drop some notes in the Wiki.

**Comment by libBletchley** [comment]
Debian Stretch was using systemd since day 1.  The how-to-forge approach was working in Debian Stretch until recently, which is what put me on the search that lead to your project.  I just discovered that I needed to remove the `dnsmasq` package.  I now have version `1.6.2-3` of the `network-manager` package.  Since that's where the dnsmasq config now lives, i thought perhaps that's what changed.. but when i look at my logs, my network manager was never upgraded since installing Stretch.  So that can't be the relevant tool.

Perhaps it was the `dnsmasq` package that broke things.  My logs show it was upgraded to version `2.76-5+deb9u1` a week ago.  It's possible that's where things broke.

**Comment by Bylon** [comment]
Ok, so that would be the 16.04 walkthrough then.

Up to 14.04 dnsmasq displayed a strange behaviour. The limited instance launched through Networkmanager was almost impossible to parametrize, that is why  we needed a second full dnsmasq. It worked until 12.04 included, but since 14.04 that is when things became strange because the two instances of dnsmasq could conflict which made DNS leak... hence the correct parametrization in this project.

Since 16.04, Networkmanager is now using a more complete version of dnsmasq. It now supports enough parametrization so that we don't need a second dnsmasq anymore and the one launched with Networkmanager is now enough for our middlebox.

I guess that might be that!

In 16.04 we got:
```
$ dpkg -s Network-Manager
Version: 1.2.6-0ubuntu0.16.04.1
```
Which pulls dnsmasq-base
```
$ dpkg -s dnsmasq-base
Version: 2.75-1ubuntu0.16.04.4
```

dnsmasq-base 2.75 is now enough for what we need, so we don't need full dnsmasq anymore (it would break things!). See:
```
$ dpkg -s dnsmasq
dpkg-query: package 'dnsmasq' is not installed and no information is available
```

**Comment by Bylon** [comment]
So, since you got it working, I guess I can close this ticket!

Thanks for confirming you got it working on Stretch.

**Comment by libBletchley** [comment]
> So, since you got it working, I guess I can close this ticket!

Well I can see how the ticket would be taken as a support request.. but I actually intended it to be a bug report against the docs for using distro-specific version references.  Anyway, no worries.

**Comment by Bylon** [comment]
You are right, I reopened it and will add as a reference the version used if this information can help people from other distro to adapt.

Same as Debian, that will be done... when it's done, since I'm still working on the other ticket about IPV6!

**Comment by Bylon** [comment]
Versions of the main components we use for TorMiddlebox were added to [the main Wiki page](https://github.com/Bylon/TOR_Middlebox/wiki)

This closes the issue.

If you need other components versions to adapt to some distributions, please feel free to open another ticket.
