### ISSUE TITLE
add a testing command

### ISSUE THREAD

**Issue by libBletchley** [Bylon/TOR_Middlebox#3]
I'm not sure how to update your wiki.  I forked it, but then the forked wiki is empty.  Anyway, you might want to add this to the wiki:

**Testing**
Launching a VM such as virtualbox can be painfully slow.  To test your middlebox quickly, install the `firejail` package and run this one-liner:
`tmpdir=$(mktemp -d) && XDG_DOWNLOAD_DIR=$tmpdir firejail --private="$tmpdir" --net=vnet0 lynx -dump -nolist http://check.torproject.org`

**Comment by Bylon** [comment]
There is a nice reading about unprivileged user's containers here: https://github.com/projectatomic/bubblewrap

In summary, it is still a work in progress, even at the kernel level.

So since Tor is dedicated to anonymity, we wouldn't want to break that with miscreant using vulnerabilities on half baked features.

That being said, it is very nice and lightweight. I am still fighting to get firefox work completely well under the isolation of firejail. There is a pulseaudio bug: when lauching a separate firefox in the firejail, it kills the audio on the host! Fortunately that is known bug with a workaround: https://firejail.wordpress.com/support/known-problems/

Now I am fighting to make the separate firefox display it's menu in the title bar, as Unity settings allow.

Once I have ironed that out, I'll add the suggestion on the wiki with a **caution advise** considering the state of progress of this sort of isolation. Indeed, not having to launch a full VM just to get a page that is blocked by your addons on your main firefox is a neat trick.

**Comment by Bylon** [comment]
I have added much more that the test command.

We now have an experimental "Firefox -Middlebox". That is we can run a separate window of firefox that routes all traffic to tor, without the need to launch a full VM.

The tutorial is here: https://github.com/Bylon/TOR_Middlebox/wiki/Firefox---Middlebox-tricks

I am not closing this issue yet, since I still have some "Todos" about the bug firejail triggers.

Two of those bugs have workaround, the third does not have any workaround so far.

**Comment by Bylon** [comment]
Confirmed that the workaround with 2 interfaces vnet0 and vnet1 works for having both firejail and VM.

Since I changed my script "manually" for now, I'll close that with the new version of the script that is a work in progress!

**Comment by Bylon** [comment]
Firejail is now automatically supported by version 2.0.0

The user can then have a "testing command" without having to run a full VM, or play with things like firefox inside the sandbox.

This closes the ticket.
